# -*- coding: utf-8 -*-
"""Multiplication_app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVrop08y-4fBnohPzARrXw2cB7S1pTj8
"""

import streamlit as st

def main():
  st.title("Multiply Two Numbers")
  
  html_temp = """
  <div style="background-color:Maroon;padding:10px">
  <h2 style="color:white;text-align:center;">Multiplication of two given numbers using Streamlit</h2>
  </div> """
  
  st.markdown(html_temp,unsafe_allow_html=True)
  
  num1 = st.number_input("Number 1")
  num2 = st.number_input("Number 2")
  if num1==0 or num2==0:
      result=0
  else:
      result=num1*num2
      
  st.success('Multiply of these two numbers is {}'.format(result))
  
  if st.button("Made By"):
      st.text("Neeraj Yadav")
      st.text("21f1005729")

if __name__=='__main__':
  main()
